### ISSUE TITLE
The dlls conflict with the ones present in other packages

### ISSUE THREAD

**Issue by sebas77** [xoofx/UnityNuGet#10]
you must be aware of this

E:/Archive/Prgdir/Svelto/Svelto.MiniExamples/Example1-DoofusesMustEat/Iteration2-Burst/Library/PackageCache/com.unity.collections@0.3.0-preview.0/System.Runtime.CompilerServices.Unsafe.dll, E:/Archive/Prgdir/Svelto/Svelto.MiniExamples/Example1-DoofusesMustEat/Iteration2-Burst/Library/PackageCache/org.nuget.system.runtime.compilerservices.unsafe@4.5.0/System.Runtime.CompilerServices.Unsafe.dll

however I have noticed that burst also uses Unsafe.dll, I am not sure how it doesn't conflict in that case

**Comment by xoofx** [comment]
Yes, that's a problem in Entities, I told them they should do it differently a few months ago, but nobody got the time on their side to fix it yet.

Burst doesn't have this problem because the Unsafe DLL was made internal and renamed, so it can't have any conflict.

**Comment by sebas77** [comment]
Thanks Alexander, is there a way for me to achieve the same result you did
in order to use the buffer and memory dlls? They don't conflict with other
dlls but they don't recognise the unsafe dll used by entities so I am not
sure what the best strategy would be .
