### ISSUE TITLE
Add info about server-update to readme

### ISSUE THREAD

**Issue by ComradeVanti** [xoofx/UnityNuGet#100]
As I understand it, based on #56, the registry is uploaded to the server manually by @xoofx once in a while. I also found the CI pipeline which seems to contain steps to publish to the server, but skipped them for my pull-request. I am now a little unsure on how and when the server is updated.

Could we add some info about this to the FAQ section in the readme?

Thanks!

**Comment by xoofx** [comment]
Indeed, fixed by commit dd64ab9

**Comment by xoofx** [comment]
And I pushed a new tag as well 🙂
