### ISSUE TITLE
New tag

### ISSUE THREAD

**Issue by ComradeVanti** [xoofx/UnityNuGet#103]
Hey. I'm not sure what the proper channel is for this, but could we have a new tag to get the new packages on the server?

Maybe you could add some hooks to automatically create new tags whenever you merge a PR?

Thanks a lot!

**Comment by xoofx** [comment]
> Hey. I'm not sure what the proper channel is for this, but could we have a new tag to get the new packages on the server?

I pushed a new tag.

> Maybe you could add some hooks to automatically create new tags whenever you merge a PR?

I would prefer that the server pulls directly from the GitHub file, only when the server version doesn't change. But I don't have time to develop such thing. Feel free to open a separate issue.
