### ISSUE TITLE
Support pre-release packages with versions that compliy with Semantic Versioning.

### ISSUE THREAD

**Issue by cdytoby** [xoofx/UnityNuGet#104]
latest unity version already supports showing pre-release packages, so having them in project should not be a problem. 

This will be useful when we're using self-hosted service and use our own nuget server.

**Comment by xoofx** [comment]
I will decline for similar reason than originally discussed in #3

**Comment by cdytoby** [comment]
@xoofx that reason is not valid anymore, the package manager UI can already display pre-release packages. 

Or are there any other reasons I missed?

**Comment by xoofx** [comment]
> UI can already display pre-release packages.

Afair, only packages from Unity. 

> Or are there any other reasons I missed?

NuGet postfix for preview is not compatible with npm/Unity, it would require to remap them to something that could work... but I'm not even sure that Unity support any kind of preview beyond the one that are officially released by Unity. I will have to double check with folks from Unity.

Lastly, for the publish UnityNuGet service provided, I would not allow preview packages for the reason that I don't want to pollute the publish storage with lots of preview packages (Some NuGet package can publish a new package on every commit).

**Comment by cdytoby** [comment]
I do agree about public UnityNuGet service. What I ask for is not for public, but for self-hosted service. 

The company I worked for has multiple nugets in our own nuget feed, and it's a pain to use them in Unity. This is a better solution than creating a new npm package source for each nuget.
