### ISSUE TITLE
Support multiple NuGet source feeds

### ISSUE THREAD

**Issue by cdytoby** [xoofx/UnityNuGet#105]
Currently this project only support a single nuget instance. It would be great if it supports multiple nuget instances.

**Comment by xoofx** [comment]
> supports multiple nuget instances

You mean NuGet source feed?

**Comment by cdytoby** [comment]
Yes, that's what I mean. sorry for the confusion.

**Comment by bdovaz** [comment]
Check this Docker example:

https://github.com/xoofx/UnityNuGet/tree/master/examples/docker

You can configure your NuGet.config file.

**Comment by bdovaz** [comment]
@cdytoby this is already implemented in #112 so you can close this issue.
