### ISSUE TITLE
Same name DLL collisions

### ISSUE THREAD

**Issue by ComradeVanti** [xoofx/UnityNuGet#106]
Im using UnityNuGet over OpenUPM to import one of my packages. 

The imported package contains two DLLs, one for .netstandard 2.1 and one for 2.0. They have correct constraints set so only one is ever actually built depending on the unity version.

However as can be seen in [this](https://issuetracker.unity3d.com/issues/identical-dll-files-targeting-different-builds-with-define-constraints-conflict-with-each-other-when-building-a-project) unity issue and other ones, there is currently a bug which prevents building to android (and i believe anything other than standalone) because of name conflicts.

The DLL plugin-conflict resolver does not understand that one of these DLLs will not be included and fails the build because the DLLs have the same name. 

The generation of the multiple DLLs is part of this service correct? If so, could we add a flag to the registry to only build .netstandard 2.0 instead of both? An other option would be to add the .netstandard version (2.0 or 2.1) to the end of the DLL name in order to make their names different.

**Comment by favoyang** [comment]
What's the troubled NuGet package name?

**Comment by bdovaz** [comment]
You will have to wait:

https://issuetracker.unity3d.com/issues/found-plugins-with-same-names-error-is-thrown-for-the-microsoft-extensions-logging-package-when-building-on-android-platform

Reported by myself a few months ago.

It seems that they have finally managed to fix it and are introducing the solution in each release.

**Comment by ComradeVanti** [comment]
> What's the troubled NuGet package name?

ComradeVanti.CSharpTools.Opt and ComradeVanti.CSharpTools.Res

**Comment by ComradeVanti** [comment]
@bdovaz Its broken for me in one of the versions that they list as fixed. Strange

**Comment by ComradeVanti** [comment]
Is putting the target framework into the DLLs name an option?

**Comment by bdovaz** [comment]
@ComradeVanti 

The only workaround I have done in some cases although it is very tedious is to move everything from Library/PackageCache/org.nuget.* to Packages folder and delete all netstandard2.0 or netstandard2.1 folders (depends on what backend you use and your version of Unity).

This way you remove the duplicates and everything works as it should but you lose the fact that you can easily update the packages afterwards.

It is clearly a temporary workaround.

**Comment by ComradeVanti** [comment]
@bdovaz Got it, will do. Thanks for the suggestion. Im still thinking about if we could simply add the backend version to the name of the generated DLL. so it would be like My.Dll2.0 and My.Dll2.1. That way they would have different names.

**Comment by bdovaz** [comment]
I wouldn't make that change to this library due to the fact that it is a bug in Unity that they are close to fixing.

**Comment by ComradeVanti** [comment]
Alright, fair enough. Hope the new LTS rolls around soon. Thanks for the comments, I'll close the issue.
