### ISSUE TITLE
Your feed (unitynuget-registry.azurewebsites.net) appears to be broken

### ISSUE THREAD

**Issue by Auros** [xoofx/UnityNuGet#108]
All the API responses are returning 

```
{"error":"not_initialized","reason":"The server is initializing (100.0% completed). Please retry later..."}
```

I'm going to assume something is wrong with the packages loading as it's stuck at 100%..

I'm not sure how long it's been like this, but if it fixes itself I'll come back to close this issue. I thought I'd let you know if that's not the case.

**Comment by Auros** [comment]
Decided to look into it a bit more.

It looks like the package [Robots](https://www.nuget.org/packages/Robots) added a new dependency to [SSH.NET](https://www.nuget.org/packages/SSH.NET) starting at version 1.3.0 (released 19 days ago), and as that's not in the registry, it fails to initialize.

**Comment by bdovaz** [comment]
Fix #110

**Comment by bdovaz** [comment]
It seems to be working again @Auros, I think that you can close this issue:

https://unitynuget-registry.azurewebsites.net/-/all

**Comment by Auros** [comment]
Good to see. I've setup our own instance for one project I work on (with only the dependencies we need), but it's still nice to use the public feed for my persona projects.
