### ISSUE TITLE
Problem adding SQLite

### ISSUE THREAD

**Issue by KuraiAndras** [xoofx/UnityNuGet#114]
I am trying to add [NeoSmart.Caching.Sqlite](https://www.nuget.org/packages/NeoSmart.Caching.Sqlite), with the following dependencies:
- NeoSmart.Caching.Sqlite 5.0.2
- Microsoft.Data.Sqlite.Core 5.0.8
- SQLitePCLRaw.core 2.0.4
- SQLitePCLRaw.bundle_green 2.0.7
- SQLitePCLRaw.lib.e_sqlite3 2.0.7
- SQLitePCLRaw.provider.e_sqlite3 2.0.7

The server has the following warning:
```
The package `SQLitePCLRaw.lib.e_sqlite3.2.0.4` doesn't support `netstandard2.1,netstandard2.0`
```

Which is true, because as I understand [that package has the native libraries](https://nuget.info/packages/SQLitePCLRaw.lib.e_sqlite3/2.0.4) but does not have a TFM defined. How could this be solved? I tought that https://github.com/xoofx/UnityNuGet/issues/90 would have solved this. I also expect that https://github.com/xoofx/UnityNuGet/pull/109 will face the same problem with the SQLite dependencies.

**Comment by xoofx** [comment]
I think that #90 solved the case of the native libraries in the same package. Having packages with only native binaries only is likely possible, but it is not supported today.

**Comment by KuraiAndras** [comment]
So if I understand correctly, the I see the following solutions:
1. If a package has no TFM then scan for native libraries, and if it only has those the handle that and add the package
2. Add another property for the registry, something like: `"nativeOnly":true` which will cause that package to only expose the native binaries only

How do you feel about theese?

**Comment by IvanMurzak** [comment]
@KuraiAndras good job, I also want to use SQLitePCLRaw packages. Please, go on :)

**Comment by xoofx** [comment]
> 1. If a package has no TFM then scan for native libraries, and if it only has those then handle that and add the package
> How do you feel about these?

I would think that option 1. is preferrable to make it transparent as it is for mixed packages (that have .NET assemblies and runtime)

**Comment by KuraiAndras** [comment]
I started working on this, might need a little help later with #115
