### ISSUE TITLE
Support for Standard 2.1?

### ISSUE THREAD

**Issue by william-craven-pace** [xoofx/UnityNuGet#119]
I see that the readme says that a nuget package should include standard2.0 but is there plans to add support for standard2.1? Since the engine is updating to support it.

**Comment by KuraiAndras** [comment]
`netstandard2.1` is supported. This project requires `netstandard2.0` for packages in order to support a wider range of unity versions

**Comment by william-craven-pace** [comment]
Ah my mistake, I most have missed that. Thanks for the information.
