### ISSUE TITLE
Support editor only package

### ISSUE THREAD

**Issue by nowsprinting** [xoofx/UnityNuGet#121]
What do you think about following the idea?

Adding an option to registry.json. e.g., `“editor": true`.
To make the meta file, the set platform is editor only.

I think it can be useful for packages that do not work in standalone player.
e.g., Castle.Core

**Comment by Voltstro** [comment]
There is the `defineConstraints` option, which you can set it to `UNITY_EDITOR` to make it editor only.

**Comment by nowsprinting** [comment]
@Voltstro san,
Thanks!
I will try that way.
