### ISSUE TITLE
CaSe sensitivity?

### ISSUE THREAD

**Issue by dylanh724** [xoofx/UnityNuGet#124]
Your curated list shows `Scriban` (capital `S`), for example, but your README shows `org.nuget.scriban`. Does this mean everything is lowercase? camelCase? Can this be clarified? Shouldn't the curated list reflect the same style casing?

For example, is `Microsoft.Extensions.Primitives` written as `org.nuget.microsoft.extensions.primitives`?

**Comment by Voltstro** [comment]
The names in the curated list is the name of the package as it is on NuGet.

The `org.nuget.<package-name>` is the **converted** Unity package name, which is just the standard Unity package naming scheme.

**Comment by bdovaz** [comment]
Closing, it has already been perfectly explained by @Voltstro.
