### ISSUE TITLE
Registry down?

### ISSUE THREAD

**Issue by merulaxr** [xoofx/UnityNuGet#126]
Our CI had stopped working, so went to check and it was failing on all packages from this registry.

https://unitynuget-registry.azurewebsites.net/registry.json currently reads:
`{"error":"not_initialized","reason":"The server is initializing (100.0% completed). Please retry later..."}`
And has been this way for over 12h.

**Comment by xoofx** [comment]
Yes, it's related to this [issue](https://github.com/xoofx/UnityNuGet/issues/118#issuecomment-1209631012)

Gonna try to see later today if I can push a temp fix.

**Comment by xoofx** [comment]
Gonna try to fix it with d574b8f4dbf031c847c2352501386bb1fe8468cf, let's see how it goes...

**Comment by merulaxr** [comment]
CI is back up and working, thanks!
