### ISSUE TITLE
About Asmodat.Standard (package version ranges)

### ISSUE THREAD

**Issue by bdovaz** [xoofx/UnityNuGet#127]
@xoofx I have seen this commit and its reasoning:

https://github.com/xoofx/UnityNuGet/commit/741d1a7b48abf680cc31a45a29a8318037975030

I understand but we should avoid breaking changes as big as removing packages from the registry that projects currently depend on.

We could create:

1. simple case, array of supported versions:

```json
"Asmodat.Standard.SSH.NET": {
    "listed": true,
    "version": "1.0.0.1",
    "supportedVersions": [
      "1.0.0.1"
    ]
},
```

Cons: having to maintain it manually

2. More advanced case, support ranges of versions:

https://docs.microsoft.com/en-us/nuget/concepts/package-versioning#version-ranges

Cons: Understanding the syntax of NuGet version ranges

**Comment by KuraiAndras** [comment]
I think version ranges would generally be better but there are edge cases too. What if a packages has netstandard support for a while goes to net6 then goes back to netstandard. To property support this I think this would need to support multiple ranges.

**Comment by bdovaz** [comment]
Until the problem does not arise we are not going to complicate ourselves.

For the moment I have seen that the Version property of the PackageEntry class is already of type VersionRange: https://github.com/bdovaz/UnityNuGet/blob/master/src/UnityNuGet/RegistryEntry.cs#L19

So I have made a PR that adds again the package but limiting the maximum version: https://github.com/xoofx/UnityNuGet/pull/128

If we see in the future that this package (or any other) returns again to add compatibility with .NET Standard 2.0 we may have to implement the multiple version ranges.

**Comment by xoofx** [comment]
> @xoofx I have seen this commit and its reasoning:

Yeah, sorry, when investigating the problem, I found lots of logs in the package because of it, and I was annoyed by it so I removed it to lower the amount of logs, but because now the commit d574b8f4dbf031c847c2352501386bb1fe8468cf is not making this an error anymore, it's ok to re-add this package.

**Comment by bdovaz** [comment]
When possible @xoofx upload a new version of the server to remove the breaking change that we have generated by removing the package.
