### ISSUE TITLE
Lazy generation of packages

### ISSUE THREAD

**Issue by bdovaz** [xoofx/UnityNuGet#130]
To focus the conversation generated at issue: #118:

Context: https://github.com/xoofx/UnityNuGet/issues/118#issuecomment-1211045928 https://github.com/xoofx/UnityNuGet/issues/118#issuecomment-1211052368

I have been investigating and no hash appears in the -/all endpoint:

https://unitynuget-registry.azurewebsites.net/-/all

It does appear when you go to a specific package endpoint:

https://unitynuget-registry.azurewebsites.net/org.nuget.system.text.json

What is not possible is to generate the "shasum" field without having previously converted the package from NuGet to UPM and calculated the hash.

My doubt would be at what moment those endpoints and fields are consumed since that is in the internal implementation of the cli / frontend of the package manager.

**Comment by Nefelim4ag** [comment]
We did some investigations internally when creating static unity registry.
Unity requests all versions for the package on the first request gets the checksum and after that goes to the URL, downloads and verifies the checksum.

So the working solution is to pull all packages, convert them, and save them.
The hacky lazy solution will be to generate "fake" checksums and "fake" (not existing tar.gz), and after requests for them - retrieve them to the cache & update metadata. We can convert the package "in-flight" and return them slowly, but the checksum will not match - anyway with lazy loading, the client must do at least 2 requests.
First for the fake sha/pkg, second for the real.
