### ISSUE TITLE
[Question] Adding new packages

### ISSUE THREAD

**Issue by StephenHodgson** [xoofx/UnityNuGet#14]
When adding new packages to the curated list, do we also have to manually add the dependencies, or does the service automatically add those to the curated list as well?

**Comment by xoofx** [comment]
Currently, no, as it requires to identify for each package what is the minimum version to starts with. A package you bring in might fetch a dependency to package A v2 while the package A v1 would still be acceptable, and the current system requires from which starting version we should expose a package (usually the package version that started to support netstandard2.0)
Not that it is impossible, just that I didn't have time to invest in this.
