### ISSUE TITLE
Adding package does not make it available on C# IDE

### ISSUE THREAD

**Issue by migralito** [xoofx/UnityNuGet#141]
Hello, sorry I don't think this is actually a bug but rather me not understanding how to use this.
I have:
- added the corresponding scoped registry in the manifest file
- opened package manager
- located a specific package. Tried with:
  - Math.NET Numerics (NuGet)
  - System.Collections.Immutable (NuGet)
- opened IDE (tried with both Rider and VS Code)
- tried to import a class from the packages:
  - ImmutableList
  - DenseMatrix
- none of the classes are being recognized in the IDE

Is there anything I'm missing?
thanks

**Comment by KuraiAndras** [comment]
Did you try regenrating the project files in the editor? Preferences/External Tools

**Comment by bdovaz** [comment]
I am closing, no further information has been provided and it is possibly a user specific problem.
