### ISSUE TITLE
Repository fails with an HTTP 500

### ISSUE THREAD

**Issue by JesseTG** [xoofx/UnityNuGet#16]
The repository seems to be live, but broken. Navigating to any URL (including to download packages) returns a 500. Here's the result of accessing https://unitynuget-registry.azurewebsites.net:

> # HTTP Error 500.30 - ANCM In-Process Start Failure
> Common solutions to this issue:
> 
> - The application failed to start
> - The application started but then stopped
> - The application started but threw an exception during startup
> 
> Troubleshooting steps:
> 
> - Check the system event log for error messages
> - Enable logging the application process' stdout messages
> - Attach a debugger to the application process and inspect
> 
> For more information visit: https://go.microsoft.com/fwlink/?LinkID=2028265

**Comment by xoofx** [comment]
Oops, indeed I broke it when upgrading too quickly to netcoreapp3.1. This should be fixed by commit 0e883f6b22b56912ca923fedfadfd2521d077147 and available in a few minutes.
