### ISSUE TITLE
Package resolution error

### ISSUE THREAD

**Issue by keijiro** [xoofx/UnityNuGet#17]
Package Manager fails to import packages via the UnityNuGet registry with the following error message.

![Screenshot from 2020-11-05 21-36-46](https://user-images.githubusercontent.com/343936/98242972-9afe6300-1fb0-11eb-8209-309b112d3b73.png)

I tested with Unity 2019.4 and 2020.1 (reproduced on both of them).

You have to clear the local package cache to reproduce the issue.

**Comment by xoofx** [comment]
Yeah, I haven't check the experience in the editor since it was launched, so UPM might require new fields from the package that it was not requiring before.

**Comment by keijiro** [comment]
The strange thing is that I got the same inquiries from multiple users this week (I have never gotten one before). Did you change anything recently?

**Comment by xoofx** [comment]
The only PR merged recently that is related to changing something in the package is #12 but it's not related to this `tarball` field missing...
I would think that something has changed in UPM. I have identified for example that the field `tarball` is no longer the field `distribution` but `dist`, so could it could just that. I will try to see if that fixes it.

**Comment by xoofx** [comment]
Actually, the issue is on UnityNuGet side, a change of the underlying JSON serializer used by ASP.NET that I haven't noticed. Should be fixable soon.

**Comment by xoofx** [comment]
This should be fixed by commit 59e685dbfbfe92a749fe6c15f68763b5c7d40967
I just tested with UPM on a `2020.1.12f1` version and the packages are back in the UI.

And thanks for the report! My apology for the trouble, that was my mistake of upgrading to a newer version of ASP.NET that broke implicitly a few things.

**Comment by keijiro** [comment]
I verified that the issue was resolved. Thanks!

**Comment by hybridherbst** [comment]
Thank you two for acting so fast on this! 🎉
