### ISSUE TITLE
4 components version numbers

### ISSUE THREAD

**Issue by bdovaz** [xoofx/UnityNuGet#23]
@xoofx There are several packages like the following that have 4 components instead of 3. In our case we have been using this format for the upm package for a long time to solve this kind of packages:

major.minor.patch-revision

This is compatible with Unity (similar to 1.0.0-preview23 like Unity uses for previiew packages) and it allows to be seen in UPM window.

Are you open to this PR or do you have a better idea?

https://www.nuget.org/packages/Prism.Core/

**Comment by xoofx** [comment]
Sure, as long as the existing packages are keeping their version numbers. PR welcome.

**Comment by bdovaz** [comment]
Done!

#26
