### ISSUE TITLE
[Question] why not all packages in the curated list get served?

### ISSUE THREAD

**Issue by favoyang** [xoofx/UnityNuGet#25]
Hi @xoofx,

Thanks for maintaining this project. I found not all packages in the curated list get served.

List all packages from the register `/-/all/` endpoints (total 11 packages).

```
curl -s https://unitynuget-registry.azurewebsites.net/-/all | json -k
[
  "_updated",
  "org.nuget.automaticgraphlayout",
  "org.nuget.eflatun.expansions",
  "org.nuget.geneticsharp",
  "org.nuget.microsoft.azure.kinect.sensor",
  "org.nuget.morelinq",
  "org.nuget.newtonsoft.json",
  "org.nuget.scriban",
  "org.nuget.sharpcompress",
  "org.nuget.system.buffers",
  "org.nuget.system.memory",
  "org.nuget.system.runtime.compilerservices.unsafe"
]
```

List all packages from the curated list (total 83 packages)

```
curl -s https://raw.githubusercontent.com/xoofx/UnityNuGet/master/registry.json | json -k
```

Try to inspect one "missing" package System.Text.Json, all possible naming returns not found

- https://unitynuget-registry.azurewebsites.net/org.nuget.system.text.Json
- https://unitynuget-registry.azurewebsites.net/org.nuget.System.Text.Json
- https://unitynuget-registry.azurewebsites.net/system.text.json
- https://unitynuget-registry.azurewebsites.net/System.Text.Json

BTW, I think the register server could return HTTP 404 for the not found package, not HTTP 200.

**Comment by xoofx** [comment]
There was a deployment problem + likely a dangling state on the server. I restarted it and https://unitynuget-registry.azurewebsites.net/-/all should be fixed now.

The correct url for System.Text.Json is: https://unitynuget-registry.azurewebsites.net/org.nuget.system.text.json  (no capital case)
