### ISSUE TITLE
System.Diagnostics.DiagnosticSource is empty

### ISSUE THREAD

**Issue by JesseTG** [xoofx/UnityNuGet#27]
Import `org.nuget.system.diagnostics.diagnosticsource`, version `4.5.0` into a project and check out its directory in the package manager cache. You'll find that no DLLs are included, despite others depending on it.

**Comment by xoofx** [comment]
Hm, it's a weird one, it doesn't have a netstandard2.0 folders in it, so NuGet must probably assume that it could use net461 instead, but I don't know the rules, gonna have to ask around...

**Comment by bdovaz** [comment]
Indeed, this package is required by Microsoft.Extensions.Logging from version 5.0 onwards (when it starts targeting .net5).

https://www.nuget.org/packages/Microsoft.Extensions.Logging/5.0.0

I have only tested up to the latest 3.x which did not have this dependency and that is why I did not encounter this problem.

I am glad that you have solved it @xoofx, the truth is that it is weird that it does target that platform but then it does not provide a dll, making fallback to the closest one.

One thing @xoofx, I don't know if it's just tests you've been doing but I see that now it doesn't serve all the packages of "registry.json"?

https://unitynuget-registry.azurewebsites.net/-/all

**Comment by JesseTG** [comment]
I dragged the .NET Standard 1.3 version into my project manually and it seems to work fine. No compiler errors.

This is the relevant part of my `manifest.json`:

```
    "org.nuget.microsoft.bcl.asyncinterfaces": "5.0.0",
    "org.nuget.microsoft.extensions.configuration": "3.1.14",
    "org.nuget.microsoft.extensions.configuration.abstractions": "3.1.14",
    "org.nuget.microsoft.extensions.configuration.binder": "3.1.14",
    "org.nuget.microsoft.extensions.dependencyinjection": "5.0.0",
    "org.nuget.microsoft.extensions.dependencyinjection.abstractions": "5.0.0",
    "org.nuget.microsoft.extensions.logging": "5.0.0",
    "org.nuget.microsoft.extensions.logging.abstractions": "5.0.0",
    "org.nuget.microsoft.extensions.logging.configuration": "5.0.0",
    "org.nuget.microsoft.extensions.options": "5.0.0",
    "org.nuget.microsoft.extensions.options.configurationextensions": "5.0.0",
    "org.nuget.microsoft.extensions.primitives": "3.1.14",
    "org.nuget.system.buffers": "4.5.1",
    "org.nuget.system.diagnostics.diagnosticsource": "4.5.0",
    "org.nuget.system.memory": "4.5.4",
    "org.nuget.system.numerics.vectors": "4.4.0",
    "org.nuget.system.runtime.compilerservices.unsafe": "4.5.3",
    "org.nuget.system.threading.channels": "5.0.0",
    "org.nuget.system.threading.tasks.extensions": "4.5.4",
```

This combination of packages compiles and links without issue.

**Comment by xoofx** [comment]
> One thing @xoofx, I don't know if it's just tests you've been doing but I see that now it doesn't serve all the packages of "registry.json"?

Yes, it was a mishandling when a sha1 file was not previously written, it would error and stop processing. I have pushed a fix.
