### ISSUE TITLE
Assembly not be loaded due to mismatched assembly references version

### ISSUE THREAD

**Issue by favoyang** [xoofx/UnityNuGet#29]
Install org.nuget.system.memory@4.5.4.

Unity packman prompts:

> Assembly 'Packages/org.nuget.system.memory/System.Memory.dll' will not be loaded due to errors:
System.Memory references strong named System.Buffers Assembly references: 4.0.2.0 Found in project: 4.0.3.0.
Assembly Version Validation can be disabled in Player Settings "Assembly Version Validation"

I checked that org.nuget.system.memory@4.5.4 depends on org.nuget.system.buffers@4.5.1, and the System.Buffers.dll's assembly version is 4.0.3.0.

Disable `Assembly Version Validation` fixed the issue.

This is a problem?

**Comment by bdovaz** [comment]
It's because of strong named assemblies and versions.

I have already fought enough with this issue and thanks to Harald I managed to get that checkbox in Unity:

https://forum.unity.com/threads/editor-assembly-loading-issues-unloading-broken-assembly-could-not-load-signature.754508

**Comment by favoyang** [comment]
Seems toggle the checkbox is the desired solution, so I should close the issue?

**Comment by cdytoby** [comment]
@xoofx @favoyang Need help on this one, the answer is not clear:

"Seems toggle the checkbox is the desired solution"

I don't understand at all.

This toggle box is NOT TOGGLEABLE, how do I toggle the checkbox?

**Comment by cdytoby** [comment]
I got it. The checkbox for reference validation is in the "project setting", not in the dll import setting.

**Comment by Rabadash8820** [comment]
For those coming across this issue later, the checkbox mentioned above is: "Project Settings > Player > Other Settings > Configuration > Assembly Version Validation (editor only)". The tooltip on this checkbox is also very nice, explaining that the option only affects resolution for Strong Named assemblies.
