### ISSUE TITLE
unity core crash error

### ISSUE THREAD

**Issue by guguguguman** [xoofx/UnityNuGet#296]
Hi I updated the recently released Amazon GameLift Web SDK version 5.1 to build the GameLift feature of Amazon Web Services into Unity Server and I found this error, it seems that there is a conflict with System.Security.Permissions in unity core which is included in this unity nuget, is there a solution for this error?

here the error msg in unity editor
-----------
Library\PackageCache\com.unity.services.core@1.6.0\Editor\Core\Configuration\ProjectConfigurationBuildInjectorWithPlayerProcessor.cs(43,50): error CS0433: The type 'FileIOPermission' exists in both 'System.Security.Permissions, Version=7.0.0.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51' and 'mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089'

**Comment by guguguguman** [comment]
i use Pakage Manager add scoped registry
and unity verion 2022.2.15 , 2021.3.14 , 2021.3.16 these three version not work

**Comment by SwatX18** [comment]
Same problem, I don't know what to do...
