### ISSUE TITLE
Support packages with only preview versions

### ISSUE THREAD

**Issue by DaZombieKiller** [xoofx/UnityNuGet#3]
I figured I'd open this issue since there isn't one for it yet.

I'd like to be able to use [Microsoft.Bcl.HashCode](https://www.nuget.org/packages/Microsoft.Bcl.HashCode/) through this service until .NET Standard 2.1 rolls out and makes its way into Unity. Currently that cannot be done as it only has preview versions.

Is there any major issue currently blocking the support of these kinds of packages?

**Comment by xoofx** [comment]
Previews are not manageable in Unity, the UI would just not support that, and I don't think we can use the same naming convention that NuGet is allowing (I believe the Unity one is more restrictive)

But now that `Microsoft.Bcl.HashCode` 1.0.0 is stable, it could be added to the registry
