### ISSUE TITLE
Registry Down

### ISSUE THREAD

**Issue by Cabskee** [xoofx/UnityNuGet#315]
https://unitynuget-registry.azurewebsites.net/registry.json
https://unitynuget-registry.azurewebsites.net/status

Registry is currently down (or stuck at 38%) with a ton of warnings.

**Comment by Cabskee** [comment]
It has progressed to 38.5% so it doesn't seem stuck, but it seems a little odd the registry would go completely down while it updates. Many of our devs are unable to boot our project because they cannot access the registry.

**Comment by bdovaz** [comment]
In progress...
