### ISSUE TITLE
Unity not adding NET_STANDARD_2_0 define on UWP platform

### ISSUE THREAD

**Issue by bdovaz** [xoofx/UnityNuGet#32]
On each *.dll there is a meta defining NET_STANDARD_2_0 constraint:

https://github.com/xoofx/UnityNuGet/blob/master/src/UnityNuGet/UnityMeta.cs#L41

When switching to UWP it doesn't add NET_STANDARD_2_0 define, it adds NET_4_6 instead and I have .NET Standard 2.0 scripting backend set. According to this page it should be added:

https://docs.unity3d.com/Manual/PlatformDependentCompilation.html

On each *.dll file In define constraints there is a red icon saying that define constraint is incompatible. Same goes to *.csproj files, it doesn't include NET_STANDARD_2_0 define.

I tried to workaround it by adding a "csc.rsp" file with -d:NET_STANDARD_2_0 but it only works for *.csproj files (it includes correctly that define) but with *.dll files I still get that red icon saying that define constraint is incompatible.

I have reported it to Unity @xoofx maybe you can pull some strings (Case 1334636).

For now I think there is not much to do despite of copying packages from Library/PackageCache to Packages and remove manually that define constraint on each *.dll file.

**Edit:** https://issuetracker.unity3d.com/issues/uwp-not-adding-net-standard-2-0-define

**Comment by xoofx** [comment]
As per commit c3eb9e1d3484ffc43f0ed7dee6e96a563344768a the constraint is removed, so it should fix this issue
