### ISSUE TITLE
R3 not showing up in package manager

### ISSUE THREAD

**Issue by shiena** [xoofx/UnityNuGet#324]
R3 has been added by #316 but it does not showing up in package manager and [`/-/all` API endpoint](https://unitynuget-registry.azurewebsites.net/-/all).

**Comment by hesselmonk** [comment]
Nor do any of the other packages added after that (https://github.com/xoofx/UnityNuGet/pull/322 and https://github.com/xoofx/UnityNuGet/pull/319)

**Comment by shiena** [comment]
Thank you for updating the service. I was able to install R3 from the package manager.
