### ISSUE TITLE
Unable to add package [org.nuget.awssdk.core@3.7.304]... shasum check failed

### ISSUE THREAD

**Issue by aallbrig** [xoofx/UnityNuGet#372]
Tried installing the AWS SDK in my unity project but encountered the issue below.

![Screenshot 2024-06-09 at 7 02 26 PM](https://github.com/xoofx/UnityNuGet/assets/3106250/b8f1f770-aea3-483b-9536-bac0fb73cb5f)

Looking at the tags from the source aws github repo (https://github.com/aws/aws-sdk-net), it looks like the version in this project is behind by quite a few versions (see: https://github.com/xoofx/UnityNuGet/blob/master/registry.json#L99). The latest AWS SDK version is `3.7.304.13`, but this project references `3.7.302.8` (see: https://www.nuget.org/packages/awssdk.core/#versions-body-tab). I wonder if upgrading would help resolve the issue?

**Comment by bdovaz** [comment]
The error you get has nothing to do with what you say: https://github.com/xoofx/UnityNuGet?tab=readme-ov-file#verify-installation

Although in the `registry.json` file you see a version, it does not mean that this version is the last one: https://github.com/xoofx/UnityNuGet?tab=readme-ov-file#adding-a-package-to-the-registry

**Comment by aallbrig** [comment]
@bdovaz Thanks, clearing cache (aka `rm -rf $HOME/Library/Unity/cache/npm/unitynuget-registry.azurewebsites.net`) and reopening unity allowed me to successfully install AWSSDK Core. Thanks for the help!


![Screenshot 2024-06-10 at 6 16 29 AM](https://github.com/xoofx/UnityNuGet/assets/3106250/3b96c3e3-ad9e-4f27-acf6-de435d11c999)
