### ISSUE TITLE
Registry down

### ISSUE THREAD

**Issue by shiena** [xoofx/UnityNuGet#396]
https://unitynuget-registry.azurewebsites.net/status

> Error messages
> The package `Prism.Core.9.0.537` has a dependency on `Prism.Events` which is not in the registry. You must add this dependency to the registry.json file.
> 
> The package `Prism.Core.9.0.537` has a dependency on `Prism.Container.Abstractions` which is not in the registry. You must add this dependency to the registry.json file.

**Comment by bdovaz** [comment]
Can you add a PR please?
