### ISSUE TITLE
Feature request: Ability to set import settings for assemblies

### ISSUE THREAD

**Issue by JesseTG** [xoofx/UnityNuGet#40]
Some NuGet assemblies would be useful, but only on certain platforms. NSubsitute, for instance, will only work within the Editor or on Mono-powered builds, as it uses `System.Reflection.Emit`; it would need to have all platforms except for the Editor and Standalone excluded, plus it would need to test for whatever the`#define` for Mono builds is.

**Comment by xoofx** [comment]
Agreed. That would require a change to the registry to allow define the constraints and platforms. PR Welcome.

**Comment by bdovaz** [comment]
About question 2.

I made a PR a few weeks ago to make it configurable: https://github.com/xoofx/UnityNuGet/blob/master/src/UnityNuGet.Server/appsettings.json#L8

**Comment by JesseTG** [comment]
> About question 2.
> 
> I made a PR a few weeks ago to make it configurable: https://github.com/xoofx/UnityNuGet/blob/master/src/UnityNuGet.Server/appsettings.json#L8

Ooh, neat, thanks!

**Comment by JesseTG** [comment]
@xoofx Now that #59 has knocked out a good chunk of this feature request, do you happen to know anything about this?

> 4. Is there an authoritative reference for `platformData`'s structure? Or at least some `internal` class in `UnityEditor.dll` that I can peek into?
