### ISSUE TITLE
Repository web site seems to be down 

### ISSUE THREAD

**Issue by mhjort** [xoofx/UnityNuGet#415]
Url https://unitynuget-registry.azurewebsites.net/

Gives error 403 page at the moment.

**Comment by xoofx** [comment]
Yes, for some reason it has reached the spent limit on Azure ($150/month), so it is blocking the service (I think it will reset on Monday).

**Comment by mhjort** [comment]
Thanks for the info! It seems to work now.

**Comment by bdovaz** [comment]
@xoofx is there anything that can be done to control this limit? Because this time it has happened at the end of the month and it has been quick to restore but if it happens before it can be a problem...

**Comment by xoofx** [comment]
> is there anything that can be done to control this limit?

What do you mean by control? This limit is the credit I'm getting from my MVP account.

**Comment by xoofx** [comment]
> @xoofx I mean if the usage is calculated exclusively by the requests to this service or if there is some other criterion that can be “optimized” so that the cost is lower and there are no service interruptions.

It includes other services that I also provide (e.g [babelmark](https://babelmark.github.io/)), but I believe that UnityNuGet is taking the most part of it (it includes bandwidth, storage, machine...etc.). Don't think that there is much to optimize unfortunately.

Also to consider, If I lost my MVP, I would have to shutdown this service.

**Comment by bdovaz** [comment]
Yes, it is clear that for a “serious use” it is necessary to host it on your own and not to depend on you obviously.
