### ISSUE TITLE
Is it possible to add all google cloud package?

### ISSUE THREAD

**Issue by Thaina** [xoofx/UnityNuGet#429]
I want to use firebase for making unity editor admin extension to manage firestore in side unity. But I think all google cloud dotnet package would be great to have too

https://github.com/googleapis/google-cloud-dotnet

**Comment by bdovaz** [comment]
You can create a PR with all the packages you specifically need.

**Comment by Thaina** [comment]
Not sure if I am doing this right

https://github.com/xoofx/UnityNuGet/pull/430/

**Comment by Thaina** [comment]
@bdovaz Have added another dependency

**Comment by Thaina** [comment]
Are there anyway I can trigger action by myself?
or at least test the action in my local machine

**Comment by bdovaz** [comment]
You can open the VS solution file and run all tests by yourself

**Comment by Thaina** [comment]
Is it possible in vscode?

**Comment by Thaina** [comment]
@bdovaz Just yesterday MessagePack package which not relate to me was update to 3.0.300 https://www.nuget.org/packages/MessagePack/3.0.300#versions-body-tab

And it has dependency on MessagePackAnalyzer which has no framework support or native lib https://www.nuget.org/packages/MessagePackAnalyzer/#supportedframeworks-body-tab

And this make by push fail unrelate to my request. How can I fix it?

**Comment by bdovaz** [comment]
Create another PR with that Message pack dependency first

**Comment by Thaina** [comment]
> Create another PR with that Message pack dependency first

It's not possible. As I said that Message pack dependency has no framework support or native lib

**Comment by Thaina** [comment]
I have try to make it by set maxversion on `MessagePack` to use only version below 2 which have no dependency on that analyzer. And it pass the RegistryTests in my machine

**Comment by bdovaz** [comment]
Done https://github.com/xoofx/UnityNuGet/pull/430
