### ISSUE TITLE
Registry down

### ISSUE THREAD

**Issue by mikeage** [xoofx/UnityNuGet#438]
http://unitynuget-registry.azurewebsites.net is returning a 403 :-/

**Comment by bdovaz** [comment]
@xoofx?

**Comment by xoofx** [comment]
Yes, it is down again because of spending limits, should recover tomorrow

**Comment by bdovaz** [comment]
Is there anything that can be done to reduce that cost @xoofx? The limit is the cost from December 1-10 or just from yesterday?

**Comment by mikeage** [comment]
> Yes, it is down again because of spending limits, should recover tomorrow

Thanks. Are the spending limits per UTC day, or per day in a specific region, or per-30 day period, or...?

(trying to know when it's safe to rerun a bunch of my CI jobs ;-) )

**Comment by mikeage** [comment]
thanks!
