### ISSUE TITLE
Remove NET_STANDARD_2_0 from Define Constraints

### ISSUE THREAD

**Issue by rugbbyli** [xoofx/UnityNuGet#52]
Currently all package assembly have a `NET_STANDARD_2_0` definition , which let unity reference them only when `API compatibility level` set to `.NET Standard 2.0`.  

But `.NET 4.x` api level was compatible with `.NET Standard 2.0`, means if an assembly working under `.NET Standard 2.0`, it also working under `.NET 4.x`.

So there's no reason to limit packages to `.NET Standard 2.0`.

If you have some other thinking, please let me know, thanks.

**Comment by xoofx** [comment]
Agreed. Note also that in the future, Unity will drop support for .NET 4.x.
