### ISSUE TITLE
When are packages synchronized with registry.json?

### ISSUE THREAD

**Issue by Auros** [xoofx/UnityNuGet#56]
[This PR](https://github.com/xoofx/UnityNuGet/pull/51) which adds Serilog was merged into `master` 7 days ago, yet it's not on the package list nor [the registry](https://unitynuget-registry.azurewebsites.net/-/all).

Is there a specific time in which the changes are applied to the live registry?

**Comment by xoofx** [comment]
When I push a new version to the server. The server doesn't synchronize directly with the registry.
I need to finish a few details for the new server (related to .NET Standard 2.1 support) before pushing a new version and as my sparetime is very limited these days, that explains why the server hasn't been updated yet. I'm gonna try to update last bits this morning.

**Comment by Auros** [comment]
Thanks.
