### ISSUE TITLE
Why Asmodat.Standard.SSH.NET it's removed?

### ISSUE THREAD

**Issue by bdovaz** [xoofx/UnityNuGet#58]
@xoofx As of the following commit it's removed:

https://github.com/xoofx/UnityNuGet/commit/4f97b84047ef112c5d50f9aaa0ccd8c73af081ef

Why is that?

There is no explanation in that commit.

**Comment by xoofx** [comment]
Because there was a failure on the server. and wanted to check why. It seems not related. I will check later today why the server doesn't start while the tests passes.

**Comment by bdovaz** [comment]
Okay, no problem.

When you have solved it please restore this change as we use this package.
