### ISSUE TITLE
New release?

### ISSUE THREAD

**Issue by JesseTG** [xoofx/UnityNuGet#78]
When you get a chance, would you be able to push a new release of this repo to production? There've been some changes made since June that I'd like to take advantage of. Thank you!

**Comment by xoofx** [comment]
>  When you get a chance, would you be able to push a new release of this repo to production? There've been some changes made since June that I'd like to take advantage of. Thank you!

Yep, but note that many changes were already published on Oct 5th (0.12.0)

Pushing the new server right now.
