### ISSUE TITLE
System.Reactive?

### ISSUE THREAD

**Issue by Thaina** [xoofx/UnityNuGet#79]
I wish it could be used, Are there any problem about this package? https://www.nuget.org/packages/System.Reactive/

**Comment by KuraiAndras** [comment]
I'll look into it

**Comment by bdovaz** [comment]
There is a problem. It has the following dependency:

https://www.nuget.org/packages/System.Runtime.InteropServices.WindowsRuntime/

And doesn't target .NET Standard 2.0.

**Comment by Thaina** [comment]
@bdovaz Thank you very much for your clarification

Still, currently now unity are moving to dotnet5/6 and netstandard 2.1 so are there any chance this project would migrate to that or made dual support in some way? Since `System.Reactive` in dotnet5 has been removed dependency on `WindowsRuntime` already

**Comment by bdovaz** [comment]
Unity since 2021.2.x supports .NET Standard 2.1, from there to get to implement .NET 6 is quite some time, with a lot of luck it would be for 2022.2.x and but nothing is certain ....
