### ISSUE TITLE
Missing dependencies for org.nuget.validation@2.5.42

### ISSUE THREAD

**Issue by seetyewsiang** [xoofx/UnityNuGet#82]
Got the following error message when trying to install org.nuget.validation@2.5.42.

[Package Manager Window] Unable to add package [org.nuget.validation@2.5.42]:
  Package org.nuget.validation@2.5.42 has invalid dependencies or related test packages:
    org.nuget.system.runtime.interopservices (dependency): Package [org.nuget.system.runtime.interopservices@4.3.0] cannot be found
UnityEditor.EditorApplication:Internal_CallUpdateFunctions () (at /Users/bokken/buildslave/unity/build/Editor/Mono/EditorApplication.cs:327)

**Comment by bdovaz** [comment]
That package depends on System.Runtime.InteropServices 4.3.0 version which does not target .NET Standard 2.0.

I have created a PR in that repo that removes that unnecesssary dependency, if it gets merged we can create another PR in this repo by upgrading the minimum version in the registry.json file to the new one:

https://github.com/AArnott/Validation/pull/96
