### ISSUE TITLE
Will this cause problems with unity package manager?

### ISSUE THREAD

**Issue by hichemfantar** [xoofx/UnityNuGet#88]
There's a websocket package I need and apparently I can download it through this manager.
Will installing this package manager conflict with the existing unity package manager?
If so, is there a way to install external packages using UPM?

**Comment by xoofx** [comment]
UnityNuGet is not a package manager. It is a registry for Unity UPM.

> if so, is there a way to install external packages using UPM?

That's exactly what this project is doing. 😉
