### ISSUE TITLE
Support for native libraries

### ISSUE THREAD

**Issue by visose** [xoofx/UnityNuGet#90]
I was thinking of adding a package that contains native libraries. It works well in Unity but requires modifying the .meta files so that they target the corresponding platform and architecture. Also, for Windows there might be two .dll files with the same name, one for x86 and one for x64. Only one should be enabled to work in the Editor.

I skimmed over the source code and it doesn't seem to be support for this, only for managed assemblies (I might be wrong).

Nuget supports these by placing them on specific folders, so the meta files can be adjusted depending on these folders, for example:
`runtimes\win-x64\native\file.dll`
`runtimes\win-x86\native\file.dll`
`runtimes\osx-x64\native\file.dylib`

Some more info here:
https://docs.microsoft.com/en-us/nuget/create-packages/supporting-multiple-target-frameworks

**Comment by xoofx** [comment]
Don't have personal time to work on this, but it's definitely possible and not difficult. PR welcome.

**Comment by visose** [comment]
I can make an attempt, but would it be ok if the PR is not exhaustive of everything that can go inside the runtimes folder?

This folder can contain both native and managed libraries that are platform specific. Also, mobile and other platforms besides standalone, and different versions of windows (win7, win10).

For the time being I could add only native libraries for standalone (win, linux, mac). This covers what I need at the moment, but if any one else has a package in mind with mobile or other platforms it could be added later.
